#Importing Files

In [1]:
import numpy as np
from datetime import date, timedelta

#1. Create a 3x3x3 array with random values

In [2]:
arr = np.random.rand(3,3,3)
arr

array([[[0.32514819, 0.28175728, 0.78498319],
        [0.08786185, 0.59003699, 0.49385264],
        [0.09357971, 0.79592161, 0.27565641]],

       [[0.08685296, 0.85282523, 0.63847016],
        [0.59277417, 0.65575866, 0.29649502],
        [0.02069132, 0.18531769, 0.40346595]],

       [[0.26998616, 0.09724929, 0.05149818],
        [0.81049494, 0.04293162, 0.97149385],
        [0.74506305, 0.61213541, 0.67033759]]])

#2. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
arr = np.diag(np.arange(4) + 1, k = -1)
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#3. Create a 8x8 matrix and fill it with a checkerboard pattern

In [4]:
arr = np.tile(np.array([[0,1],[1,0]]), (4,4))
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#4. Normalize a 5x5 random matrix

In [5]:
arr = np.random.random((5,5))
arr = (arr - np.mean (arr)) / (np.std (arr))
arr

array([[ 1.23948042, -0.84761634,  0.67326508,  1.74810713, -0.54532407],
       [-1.65791661,  1.18965962, -0.35350624,  0.28416601, -0.55239157],
       [ 1.52341178,  0.95381567,  0.42228264,  0.43424827,  0.487391  ],
       [-1.02709439, -0.58311001, -0.15130902, -0.66487326,  0.82597089],
       [-0.84718237, -1.14465902, -2.25406099,  0.88138064, -0.03413526]])

#5. How to find common values between two arrays?

In [6]:
arr1 = np.random.randint(0,10,10)
arr2 = np.random.randint(0,10,10)

np.intersect1d(arr1, arr2)

array([3, 5, 6, 8])

#6. How to get the dates of yesterday, today and tomorrow?

In [7]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday, today, tomorrow)

2020-08-07 2020-08-08 2020-08-09


#7. Consider two random array A and B, check if they are equal

In [9]:
arr1 = np.random.rand(3,3)
arr2 = np.random.rand(3,3)

equal = np.array_equal(arr1,arr2)
print(f'Array1:\n{arr1}\n\n')
print(f'Array2:\n{arr2}\n\n')
print(f'Equality: {equal}')

Array1:
[[0.86200537 0.54244303 0.07643054]
 [0.46191264 0.32921747 0.91231753]
 [0.52069624 0.1792288  0.49840255]]


Array2:
[[0.70179835 0.05098144 0.83263309]
 [0.07742237 0.62452266 0.82779605]
 [0.15970698 0.51222165 0.40812194]]


Equality: False



#8. Create random vector of size 10 and replace the maximum value by 0

In [10]:
arr = np.random.rand(10)
arr[arr.argmax()] = 0
arr

array([0.31827193, 0.04803612, 0.29529231, 0.18171528, 0.36755016,
       0.9361617 , 0.48637988, 0.8492991 , 0.        , 0.10585225])


#9. How to print all the values of an array?

In [18]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]



#10. Subtract the mean of each row of a matrix

In [19]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y1 = X - X.mean(axis=1).reshape(-1, 1)

print(Y)
print(Y1)

[[-4.61283087e-01  3.56714285e-01 -6.97021643e-02  5.87113444e-02
   6.52109849e-03  1.60641098e-02  3.12267640e-01 -5.63009135e-01
   3.20958894e-01  2.27570134e-02]
 [-2.71210136e-01  6.16304779e-01 -2.62341676e-01  5.51219790e-01
  -3.22502964e-01  1.79446626e-01 -2.42440888e-01 -2.61541304e-01
  -2.00312461e-01  2.13378234e-01]
 [ 5.16816872e-02 -1.82885379e-01 -1.19794795e-01  2.16399576e-01
   2.44249005e-04 -4.09228830e-01 -2.21862561e-01  1.28774781e-01
   1.62023541e-01  3.74647731e-01]
 [-3.40023652e-01  2.03776011e-03  1.57330430e-01 -1.88856234e-01
   4.70949478e-01 -2.62075976e-01  3.13690952e-01 -3.71740726e-01
   8.21778809e-02  1.36510085e-01]
 [ 2.20734667e-02  7.68154374e-02 -1.48199777e-01 -6.31024642e-02
  -2.25449366e-01  1.59823312e-01  3.15060091e-01  3.11842403e-02
  -4.01517100e-01  2.33312160e-01]]
[[-4.61283087e-01  3.56714285e-01 -6.97021643e-02  5.87113444e-02
   6.52109849e-03  1.60641098e-02  3.12267640e-01 -5.63009135e-01
   3.20958894e-01  2.27570134e-0

#11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [13]:
arr1 = np.ones(5)
arr2 = np.random.randint(0, len(arr1), 10)
arr1 += np.bincount(arr2, minlength = len(arr1))
arr1

array([4., 2., 1., 5., 3.])

#12. How to get the diagonal of a dot product?

In [20]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
print(A)
print(B)
# Slow version
prod1=np.diag(np.dot(A, B))

# Fast version
prod2=np.sum(A * B.T, axis=1)

print("diagonal of a dot product method 1 is....",prod1)
print("diagonal of a dot product method 2 is....",prod2)

[[0.3267196  0.95629203 0.48768993 0.52338937 0.56877759]
 [0.26450062 0.91257777 0.70758334 0.00819606 0.2690616 ]
 [0.82780998 0.12477885 0.00879543 0.04870195 0.56039849]
 [0.67221692 0.58689226 0.7793469  0.1147397  0.21127929]
 [0.13854031 0.98739542 0.38974362 0.78001869 0.6639166 ]]
[[0.59264489 0.62058444 0.08978505 0.68073195 0.23654899]
 [0.33778813 0.289621   0.47212036 0.89884071 0.94328625]
 [0.06017098 0.59636603 0.09314261 0.90010177 0.6472612 ]
 [0.93740919 0.86143633 0.29186105 0.37677461 0.25852667]
 [0.22941396 0.60364144 0.97331988 0.71560658 0.55499052]]
diagonal of a dot product method 1 is.... [1.16711309 1.01990244 0.69371603 1.88103757 1.78655707]
diagonal of a dot product method 2 is.... [1.16711309 1.01990244 0.69371603 1.88103757 1.78655707]


#13. How to find the most frequent value in an array?

In [21]:
Z = np.random.randint(0,10,50)
print(Z)
print(np.bincount(Z).argmax())

[6 1 9 4 2 2 9 2 8 4 5 8 8 4 1 6 0 7 5 1 5 3 7 9 9 7 0 0 6 9 0 7 1 8 8 4 4
 0 8 6 0 4 4 0 5 5 6 2 5 4]
4


#14. How to get the n largest values of an array

In [22]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5


print (Z[np.argsort(Z)[-n:]])



[9995 9996 9997 9998 9999]


#15. How to create a record array from a regular array?

In [23]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
