In [1]:
import numpy as np
from datetime import date, timedelta

#1. Create a 3x3x3 array with random values

In [2]:
arr = np.random.rand(3,3,3)
arr

array([[[0.32514819, 0.28175728, 0.78498319],
        [0.08786185, 0.59003699, 0.49385264],
        [0.09357971, 0.79592161, 0.27565641]],

       [[0.08685296, 0.85282523, 0.63847016],
        [0.59277417, 0.65575866, 0.29649502],
        [0.02069132, 0.18531769, 0.40346595]],

       [[0.26998616, 0.09724929, 0.05149818],
        [0.81049494, 0.04293162, 0.97149385],
        [0.74506305, 0.61213541, 0.67033759]]])

#2. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
arr = np.diag(np.arange(4) + 1, k = -1)
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#3. Create a 8x8 matrix and fill it with a checkerboard pattern

In [4]:
arr = np.tile(np.array([[0,1],[1,0]]), (4,4))
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#4. Normalize a 5x5 random matrix

In [5]:
arr = np.random.random((5,5))
arr = (arr - np.mean (arr)) / (np.std (arr))
arr

array([[ 1.23948042, -0.84761634,  0.67326508,  1.74810713, -0.54532407],
       [-1.65791661,  1.18965962, -0.35350624,  0.28416601, -0.55239157],
       [ 1.52341178,  0.95381567,  0.42228264,  0.43424827,  0.487391  ],
       [-1.02709439, -0.58311001, -0.15130902, -0.66487326,  0.82597089],
       [-0.84718237, -1.14465902, -2.25406099,  0.88138064, -0.03413526]])

#5. How to find common values between two arrays

In [6]:
arr1 = np.random.randint(0,10,10)
arr2 = np.random.randint(0,10,10)

np.intersect1d(arr1, arr2)

array([3, 5, 6, 8])

#6. How to get the dates of yesterday, today and tomorrow?

In [7]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday, today, tomorrow)

2020-08-07 2020-08-08 2020-08-09


#7. Consider two random array A and B, check if they are equal

In [9]:
arr1 = np.random.rand(3,3)
arr2 = np.random.rand(3,3)

equal = np.array_equal(arr1,arr2)
print(f'Array1:\n{arr1}\n\n')
print(f'Array2:\n{arr2}\n\n')
print(f'Equality: {equal}')

Array1:
[[0.86200537 0.54244303 0.07643054]
 [0.46191264 0.32921747 0.91231753]
 [0.52069624 0.1792288  0.49840255]]


Array2:
[[0.70179835 0.05098144 0.83263309]
 [0.07742237 0.62452266 0.82779605]
 [0.15970698 0.51222165 0.40812194]]


Equality: False



#8. Create random vector of size 10 and replace the maximum value by 0

In [10]:
arr = np.random.rand(10)
arr[arr.argmax()] = 0
arr

array([0.31827193, 0.04803612, 0.29529231, 0.18171528, 0.36755016,
       0.9361617 , 0.48637988, 0.8492991 , 0.        , 0.10585225])


#9. How to print all the values of an array?

In [11]:
arr = np.ones((10, 10))
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]



#10. Subtract the mean of each row of a matrix

In [12]:
arr = np.random.rand(3,3)
arr_mean = arr - arr.mean(axis=1, keepdims=True)

arr_mean

array([[-0.26499828,  0.52183524, -0.25683695],
       [-0.1812224 , -0.06897783,  0.25020023],
       [ 0.14207158,  0.28797114, -0.43004272]])

#11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [13]:
arr1 = np.ones(5)
arr2 = np.random.randint(0, len(arr1), 10)
arr1 += np.bincount(arr2, minlength = len(arr1))
arr1

array([4., 2., 1., 5., 3.])

#12. How to get the diagonal of a dot product?

In [14]:

arr1 = np.random.randint(0,10,(3,3))
arr2 = np.random.randint(0,10,(3,3))

np.einsum("ij,ji->i", arr1, arr2)

array([67, 82, 88])

#13. How to find the most frequent value in an array?

In [15]:
arr = np.random.randint(0,10,20)
print(arr)
max(set(arr), key = list(arr).count)

[2 2 0 1 7 2 6 8 8 9 9 5 2 4 6 1 6 8 2 3]


2

#14. How to get the n largest values of an array

In [16]:

arr = np.random.randint(0,10,50)
np.bincount(arr).argmax()

0

#15. How to create a record array from a regular array?

In [17]:
arr = np.array([("Science", 88.5, 90),
                 ("Maths", 87, 99),
             ("English", 85.5, 91)])

print(arr)
print("\nRECORD ARRAY")
record = np.core.records.fromarrays(arr.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
record

[['Science' '88.5' '90']
 ['Maths' '87' '99']
 ['English' '85.5' '91']]

RECORD ARRAY


rec.array([(b'Science', 88.5, 90), (b'Maths', 87. , 99),
           (b'English', 85.5, 91)],
          dtype=[('col1', 'S80'), ('col2', '<f8'), ('col3', '<i8')])